### ISSUE TITLE
Could not parse version constraint <=2.1.x: Invalid version string "2.1.x"

### ISSUE THREAD

**Issue by kirkmadera** [francoispluchino/composer-asset-plugin#129]
I get "Could not parse version constraint <=2.1.x: Invalid version string "2.1.x"" when attempting to install jquery-modal. I am requiring "bower-asset/jquery-modal": "~0.5.2". This seems similar to #55.

The library's bower.json file specifies a version like this:
```
"jquery": "1.8.0 - 2.1.x"
```

https://github.com/kylefox/jquery-modal/blob/master/bower.json

**Comment by hector-del-rio** [comment]
I get a similar error. 

```
[UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"
```
twbs/bootstrap@9b1a213cf758e1b60e20c59a721a63e13da098f7 introduced a change in bower.json and now looks like this:

```javascript
"dependencies": {
    "jquery": "1.9.1 - 2"
  }
```
I tried to run it through normal bower and it works as expected, so apparently the bug is somewhere in this this project.

**Comment by cvrebert** [comment]
Yup, works fine in real Bower:
```
$ bower install 'jquery#1.9.1 - 2'
bower jquery#1.9.1 - 2          cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#1.9.1 - 2        validate 2.1.4 against git://github.com/jquery/jquery.git#1.9.1 - 2
bower jquery#1.9.1 - 2         install jquery#2.1.4

jquery#2.1.4 bower_components/jquery
$
```

**Comment by alcohol** [comment]
I believe that Composer does not allow hyphen constraints (a range) to be combined with wildcard versions (such as `.*` or `.x`).

**Comment by francoispluchino** [comment]
Yes, but it's converted [here](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Converter/SemverConverter.php#L126).

You can see the test [here](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Tests/Converter/SemverConverterTest.php#L99).

But your error indicates an wildcard and not a number in the range, so, we have to convert it too.

**Comment by JustDoItSascha** [comment]
Do you know when bug could be fixed, because due to the changes of bootstrap nothing works more on our projects... ;-)

**Comment by francoispluchino** [comment]
I think I could free myself of the time this weekend, but if you want to fix it quickly, your contribution is welcome :-).

**Comment by JustDoItSascha** [comment]
Ok, I will take a look, because every yii project can't be updated right now or in general, every project with bootstrap ;-)

Maybe you have a hint for me where I can search for the error?

**Comment by francoispluchino** [comment]
@JustDoItSascha See my previous [comment](https://github.com/francoispluchino/composer-asset-plugin/issues/129#issuecomment-125523468). It is in this class that everything is converted.

**Comment by JustDoItSascha** [comment]
Ok, I fixed the issue and hope that I didn't break something else. See pull request https://github.com/francoispluchino/composer-asset-plugin/pull/137

**Comment by pkbhadkoliya** [comment]
Is this bug fixed? pull request #137 is merged?

**Comment by cvrebert** [comment]
Bower's docs have been updated to clarify the version range syntaxes that need to be supported:
https://github.com/bower/bower.json-spec/pull/49
(TL;DR: https://github.com/npm/node-semver#ranges)

**Comment by francoispluchino** [comment]
Fixed by #137.

**Comment by re8us** [comment]
still have this error. may be i do something wrong?
installing new yii2:
```
curl -sS https://getcomposer.org/installer | php
php composer.phar require "fxp/composer-asset-plugin:dev-master"
php composer.phar create-project yiisoft/yii2-app-basic core -v

Installing yiisoft/yii2-app-basic (2.0.4)
  - Installing yiisoft/yii2-app-basic (2.0.4)
    Loading from cache
    Extracting archive

Created project in core
Loading composer repositories with package information
Installing dependencies (including require-dev)
Adding VCS repository bower-asset/jquery
Adding VCS repository bower-asset/jquery.inputmask
Adding VCS repository bower-asset/punycode
Adding VCS repository bower-asset/yii2-pjax
Adding VCS repository bower-asset/bootstrap


                                                                          
  [UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"  
                                                                          


Exception trace:
() at phar:///home/c/user/mysite/333/composer.phar/src/Composer/Package/Version/VersionParser.php:461
Composer\Package\Version\VersionParser->parseConstraint() at phar:///home/c/user/mysite/333/composer.phar/src/Composer/Package/Version/VersionParser.php:257
Composer\Package\Version\VersionParser->parseConstraints() at phar:///home/c/user/mysite/333/composer.phar/src/Composer/Package/Loader/ArrayLoader.php:234
Composer\Package\Loader\ArrayLoader->parseLinks() at phar:///home/c/user/mysite/333/composer.phar/src/Composer/Package/Loader/ArrayLoader.php:124
Composer\Package\Loader\ArrayLoader->load() at /home/c/user/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:174
Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->preInitBranchPackage() at /home/c/user/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:138
...
```

**Comment by Gogolinsky** [comment]
The temp solution – rollback to prev version
> composer global require "fxp/composer-asset-plugin:1.0.1"

**Comment by re8us** [comment]
@Gogolinsky just tried – all the same

**Comment by lynicidn** [comment]
@re8us https://github.com/francoispluchino/composer-asset-plugin/pull/137#issuecomment-125757921

**Comment by re8us** [comment]
@lynicidn @Gogolinsky thanks a lot! 
Helped for me ``global require  "fxp/composer-asset-plugin:dev-master"`` (while **not** global didn't help).

**Comment by gilberson** [comment]
Does anyone could find the solution to this problem?

**Comment by francoispluchino** [comment]
See #137.

**Comment by gilberson** [comment]
Thanks

**Comment by sganz** [comment]
Ran into the same issue 

composer global require "fxp/composer-asset-plugin:1.0.1"

That fixed it up for me.

**Comment by francoispluchino** [comment]
What? `v1.0.3` does not work?

**Comment by sganz** [comment]
François - 

Sorry I didn't see the v1.0.3 was available I was just looking at the fix in this thread.  I just pulled 1.0.3 and it is OK as well. Sorry for the scare. Thanks for all your hard work as well!

Sandy
